version: "3.3"
services:
  mariadb:
    image: mariadb:10.1.44
    container_name: mariadb-10
    restart: "unless-stopped" 
    environment:
      - MYSQL_ROOT_PASSWORD=dakibadaki
      - MYSQL_ROOT_HOST=chorvi.duckdns.org
    volumes:
      - ./data-mysql:/var/lib/mysql # mysql data mounting point
      - ./sql:/root/sql # sql for export/import
    ports:
      - 3388:3388

 # phpmyadmin:
 #   image: phpmyadmin
 #   container_name: phpmyadmin
 #   restart: "no"
 #   environment:
 #    - PMA_ARBITRARY=1
 #   ports:
 #    - 3456:80
 #   volumes:
 #    - /sessions

  postgres:
    image: postgres:10.12
    container_name: postgres-10
    restart: "no"
    environment:
      - POSTGRES_PASSWORD=rahasia
      - POSTGRES_USER=pajar
    volumes:
      - ./data-postgres:/var/lib/postgresql/data # postgres data mounting point
      - ./sql:/root/sql # sql for export/import
    ports:
      - 5432:5432
    command:
      - "postgres"
      - "-c"
      - "listen_addresses=*"
  
  mongo:
    image: mongo:4.2.3
    container_name: mongo-4.2.3
    restart: "no"
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rahasia
    volumes:
      - ./data-mongo:/data/db # mongo data mounting point
      - ./sql:/root/sql # sql for export/import

  # mongo-express:
  #   image: mongo-express
  #   container_name: mongo-express
  #   restart: "no"
  #   ports:
  #     - 9091:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: rahasia

  pgadmin:
    image: dpage/pgadmin4
    container_name: pg-admin
    restart: "no"
    environment:
      - PGADMIN_DEFAULT_EMAIL=pajar
      - PGADMIN_DEFAULT_PASSWORD=rahasia
    ports:
      - 2345:80

  # portainer:
  #   image: portainer/portainer:latest
  #   container_name: portainer
  #   restart: "no"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - portainer_data:/data
  #   ports:
  #     - 4444:9000

# volumes:
#   portainer_data:

version: "3.3"
services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: daki
    restart: always
    ports:
      - 23306:3306
    environment:
      MYSQL_ROOT_PASSOWORD: "admin"
      MYSQL_DATABASE: "prueba"
    volumes:
      - ./schemas:/var/lib/mysql:rw
    networks:
      mysql_network:
        aliases:
          - mysql_host
volumes:
  schemas: {}
networks:
  mysql_network:
    name: mysql_net
    driver: bridge



version: "3.7"
services:
  mysql_db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: 'db_test'
      MYSQL_USER: 'usuario'
      MYSQL_PASSWORD: 'clave'
      MYSQL_ROOT_PASSWORD: 'clave_root'
    ports:
      - "3306:3306"
    volumes:
      - mysqldbvol:/var/lib/mysql
volumes:
  mysqldbvol: